filebeat.inputs:
  # Docker container logs
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    fields:
      environment: dev
      source: docker
    fields_under_root: true
    processors:
      - drop_event:
          when:
            or:
              - equals:
                  container.name: "logstash"
              - equals:
                  container.name: "elasticsearch"
              - equals:
                  container.name: "kibana"
              - equals:
                  container.name: "mysql-elk-8.3.0"
              - equals:
                  container.name: "kafka"
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

# Output to Logstash
output.logstash:
  hosts: ["logstash:5044"]

# Output directly to Elasticsearch (alternative)
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "filebeat-%{+yyyy.MM.dd}"

# Kibana dashboard configuration
setup.kibana:
  host: "kibana:5601"

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644