server:
  port: 8080

auth:
  service:
    base-url: http://localhost:8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Route to auth service
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**, /api/admin/**
          filters:
            - name: AuthenticationFilter

        # Route to user service
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
          filters:
            - name: AuthenticationFilter

        # Route to chatbot service
        - id: chatbot-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/ai/gemini/**
          filters:
            - name: AuthenticationFilter

        # Route to expense service
        - id: expense-service
          uri: http://localhost:8084
          predicates:
            - Path=/expense/v1/**
          filters:
            - name: AuthenticationFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
